apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: asia-southeast1-docker.pkg.dev/poc-innovation-iot/mass-artifact-registry/example-react:1.0.2
        ports:
        - containerPort: 3000
